# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        HomeBundle\Entity\User:
            algorithm: bcrypt


    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        jardins_provider:
            entity: { class : HomeBundle:User, property : username }


    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  jardins_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
